export {default as Navbar} from "./navbar/navbar"
export {default as Footer} from "./footer/footer"
export {default as Hero} from "./hero/hero"
export {default as About} from "./about/about"
export {default as Projects} from "./projects/projects"
export {default as DetailedPage} from "./detailedPage/detailedPage"